# Generated by Django 6.0.7 on 2026-08-18 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del equipo')),
                ('categoria', models.CharField(default='Masculino', max_length=80, verbose_name='Categoría')),
                ('color_principal', models.CharField(default='Rojo', max_length=50, verbose_name='Color principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del torneo')),
                ('categoria', models.CharField(default='Senior', max_length=80, verbose_name='Categoría')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de finalización')),
                ('lugar', models.CharField(max_length=200, verbose_name='Lugar')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado')], default='PROGRAMADO', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='Documento')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('posicion', models.CharField(choices=[('LIBERO', 'Líbero'), ('PUNTA', 'Punta'), ('CENTRAL', 'Central'), ('OPUESTO', 'Opuesto'), ('COLOCADOR', 'Colocador'), ('REVANCHA', 'Revancha')], default='PUNTA', max_length=20, verbose_name='Posición')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jugadores/', verbose_name='Foto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='torneos.equipo', verbose_name='Equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='torneos.torneo', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='torneos.torneo', verbose_name='Torneo'),
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('JUGADOR', 'Jugador'), ('DELEGADO', 'Delegado'), ('ARBITRO', 'Árbitro')], default='JUGADOR', max_length=20, verbose_name='Tipo')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credenciales', to='torneos.jugador', verbose_name='Jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales', to='torneos.torneo', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Credencial',
                'verbose_name_plural': 'Credenciales',
            },
        ),
    ]
