# Generated by Django 6.0.7 on 2026-08-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='tipo_persona',
            field=models.CharField(choices=[('JUGADOR', 'Jugador'), ('ENTRENADOR', 'Entrenador')], default='JUGADOR', max_length=20, verbose_name='Tipo'),
        ),
    ]
