# Generated by Django 6.0.7 on 2026-08-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('DELEGADO', 'Delegado'), ('ENTRENADOR', 'Entrenador')], default='DELEGADO', max_length=20, verbose_name='Rol'),
        ),
    ]
