# Generated by Django 6.0.7 on 2026-09-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('DELEGADO', 'Delegado'), ('ENTRENADOR', 'Entrenador'), ('TUTOR', 'Padre, madre o tutor')], default='DELEGADO', max_length=20, verbose_name='Rol'),
        ),
    ]
