# Generated by Django 6.0.7 on 2026-09-17 21:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('edad_minima', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('edad_maxima', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('monto_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dia_vencimiento', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('entrenadores', models.ManyToManyField(blank=True, limit_choices_to={'rol': 'ENTRENADOR'}, related_name='categorias_escuela', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'categoria de escuela',
                'verbose_name_plural': 'categorias de escuela',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=30, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_inscripcion', models.DateField(default=django.utils.timezone.localdate)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('telefono', models.CharField(blank=True, max_length=25)),
                ('tutor_nombre', models.CharField(max_length=160)),
                ('tutor_parentesco', models.CharField(blank=True, max_length=60)),
                ('tutor_telefono', models.CharField(max_length=25)),
                ('tutor_telefono_alternativo', models.CharField(blank=True, max_length=25)),
                ('tutor_email', models.EmailField(blank=True, max_length=254)),
                ('monto_mensual_personalizado', models.DecimalField(blank=True, decimal_places=2, help_text='Si esta vacio se usa el monto de la categoria.', max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('RETIRADO', 'Retirado')], default='ACTIVO', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos_escuela_creados', to=settings.AUTH_USER_MODEL)),
                ('entrenador', models.ForeignKey(blank=True, limit_choices_to={'rol': 'ENTRENADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos_escuela', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='escuela.categoriaescuela')),
            ],
            options={
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Primer dia del mes facturado.')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago parcial'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to='escuela.alumno')),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensualidades_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-periodo', 'alumno__apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate)),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'QR'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20)),
                ('numero_comprobante', models.CharField(blank=True, max_length=80)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('mensualidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='escuela.mensualidad')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('RECORDATORIO', 'Recordatorio de pago'), ('DEUDA', 'Aviso de deuda'), ('CONFIRMACION', 'Confirmacion de pago'), ('GENERAL', 'Mensaje general')], default='RECORDATORIO', max_length=20)),
                ('contenido', models.TextField(help_text='Variables: {alumno}, {tutor}, {categoria}, {periodo}, {monto}, {saldo}, {vencimiento}.')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=25)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='escuela.alumno')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mensualidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='escuela.mensualidad')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escuela.plantillamensaje')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='mensualidad',
            constraint=models.UniqueConstraint(fields=('alumno', 'periodo'), name='mensualidad_unica_por_periodo'),
        ),
    ]
