# Generated by Django 6.0.7 on 2026-09-17 22:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0002_plantillas_iniciales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensualidad',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='detalle_descuento',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='monto_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='numero_recibo',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='DescuentoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('MONTO', 'Monto fijo')], default='PORCENTAJE', max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='escuela.alumno')),
                ('autorizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activo', 'alumno__apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EntregaUniforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=100)),
                ('talla', models.CharField(blank=True, max_length=20)),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('DEVUELTO', 'Devuelto')], default='PENDIENTE', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniformes', to='escuela.alumno')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionDeportiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('saque', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('recepcion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('ataque', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('bloqueo', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('defensa', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('condicion_fisica', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='escuela.alumno')),
                ('evaluado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', 'alumno__apellidos'],
            },
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_sanguineo', models.CharField(blank=True, max_length=10)),
                ('alergias', models.TextField(blank=True)),
                ('lesiones', models.TextField(blank=True)),
                ('medicamentos', models.TextField(blank=True)),
                ('restricciones', models.TextField(blank=True)),
                ('seguro_medico', models.CharField(blank=True, max_length=160)),
                ('numero_seguro', models.CharField(blank=True, max_length=80)),
                ('contacto_emergencia', models.CharField(max_length=160)),
                ('telefono_emergencia', models.CharField(max_length=25)),
                ('certificado_vigente_hasta', models.DateField(blank=True, null=True)),
                ('apto_para_entrenar', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_medica', to='escuela.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=120)),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('fecha_prestamo', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_devolucion_prevista', models.DateField(blank=True, null=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PRESTADO', 'Prestado'), ('DEVUELTO', 'Devuelto'), ('PERDIDO', 'Perdido')], default='PRESTADO', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_prestados', to='escuela.alumno')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='GrupoEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dias', models.CharField(help_text='Ejemplo: Lunes, Miercoles y Viernes', max_length=120)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(max_length=160)),
                ('capacidad', models.PositiveSmallIntegerField(default=20)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('alumnos', models.ManyToManyField(blank=True, related_name='grupos', to='escuela.alumno')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='escuela.categoriaescuela')),
                ('entrenador', models.ForeignKey(blank=True, limit_choices_to={'rol': 'ENTRENADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_escuela', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['categoria__nombre', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('categoria', 'nombre'), name='grupo_unico_por_categoria')],
            },
        ),
    ]
