# Generated by Django 6.0.7 on 2026-09-17 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_completar_monto_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CERTIFICADO', 'Certificado medico'), ('IDENTIDAD', 'Documento de identidad'), ('AUTORIZACION', 'Autorizacion'), ('SEGURO', 'Seguro medico'), ('OTRO', 'Otro')], default='CERTIFICADO', max_length=20)),
                ('nombre', models.CharField(max_length=140)),
                ('archivo', models.FileField(upload_to='escuela/documentos/%Y/%m/')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='escuela.alumno')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
