# Generated by Django 6.0.7 on 2026-09-18 15:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0006_cambiohorariogrupo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='tutor_usuario',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'TUTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_escuela', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GastoEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=180)),
                ('categoria', models.CharField(choices=[('CANCHA', 'Alquiler de cancha'), ('ENTRENADORES', 'Pago a entrenadores'), ('MATERIAL', 'Material deportivo'), ('UNIFORMES', 'Uniformes'), ('SERVICIOS', 'Servicios'), ('OTRO', 'Otro')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'QR'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='escuela/gastos/%Y/%m/')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('tipo', models.CharField(choices=[('UNIFORME', 'Uniforme'), ('MATERIAL', 'Material deportivo'), ('OTRO', 'Otro')], max_length=15)),
                ('talla', models.CharField(blank=True, max_length=20)),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tipo', 'nombre', 'talla'],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'talla'), name='producto_talla_unico')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('motivo', models.CharField(max_length=180)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escuela.alumno')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='escuela.productoinventario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=80)),
                ('objeto_id', models.CharField(blank=True, max_length=40)),
                ('descripcion', models.TextField()),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_nombres', models.CharField(max_length=100)),
                ('alumno_apellidos', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('tutor_nombre', models.CharField(max_length=160)),
                ('tutor_telefono', models.CharField(max_length=25)),
                ('tutor_email', models.EmailField(blank=True, max_length=254)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('LISTA_ESPERA', 'Lista de espera')], default='PENDIENTE', max_length=15)),
                ('respuesta', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='escuela.categoriaescuela')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='escuela.grupoentrenamiento')),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_nombre', models.CharField(max_length=200)),
                ('tutor_nombre', models.CharField(max_length=160)),
                ('tutor_telefono', models.CharField(max_length=25)),
                ('estado', models.CharField(choices=[('ESPERANDO', 'Esperando'), ('CONTACTADO', 'Contactado'), ('INSCRITO', 'Inscrito'), ('CANCELADO', 'Cancelado')], default='ESPERANDO', max_length=12)),
                ('prioridad', models.PositiveIntegerField(default=1)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lista_espera', to='escuela.categoriaescuela')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lista_espera', to='escuela.grupoentrenamiento')),
                ('solicitud', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escuela.solicitudinscripcion')),
            ],
            options={
                'ordering': ['prioridad', 'fecha_registro'],
            },
        ),
    ]
