# Generated by Django 6.0.7 on 2026-09-22 02:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def crear_fichas_existentes(apps, schema_editor):
    Usuario = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    EntrenadorEscuela = apps.get_model('escuela', 'EntrenadorEscuela')
    perfiles = [
        EntrenadorEscuela(usuario_id=usuario_id)
        for usuario_id in Usuario.objects.filter(rol='ENTRENADOR').values_list('id', flat=True)
    ]
    EntrenadorEscuela.objects.bulk_create(perfiles, ignore_conflicts=True)


def eliminar_fichas(apps, schema_editor):
    apps.get_model('escuela', 'EntrenadorEscuela').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0007_alumno_tutor_usuario_gastoescuela_productoinventario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrenadorEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=120)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.localdate)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(limit_choices_to={'rol': 'ENTRENADOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='perfil_entrenador_escuela', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario__last_name', 'usuario__first_name', 'usuario__username'],
            },
        ),
        migrations.RunPython(crear_fichas_existentes, eliminar_fichas),
    ]
