from django.urls import path

from . import api_views


urlpatterns = [
    path('escuela/publico/catalogo/', api_views.CatalogoInscripcionPublicaAPIView.as_view()),
    path('escuela/publico/solicitudes/', api_views.SolicitudInscripcionListCreateAPIView.as_view()),
    path('escuela/portal-tutor/', api_views.PortalTutorAPIView.as_view()),
    path('escuela/resumen/', api_views.ResumenEscuelaAPIView.as_view()),
    path('escuela/entrenadores/', api_views.EntrenadorEscuelaListCreateAPIView.as_view()),
    path('escuela/entrenadores/<int:pk>/', api_views.EntrenadorEscuelaDetailAPIView.as_view()),
    path('escuela/categorias/', api_views.CategoriaListCreateAPIView.as_view()),
    path('escuela/categorias/<int:pk>/', api_views.CategoriaDetailAPIView.as_view()),
    path('escuela/alumnos/', api_views.AlumnoListCreateAPIView.as_view()),
    path('escuela/alumnos/<int:pk>/', api_views.AlumnoDetailAPIView.as_view()),
    path('escuela/mensualidades/', api_views.MensualidadListCreateAPIView.as_view()),
    path('escuela/mensualidades/<int:pk>/', api_views.MensualidadDetailAPIView.as_view()),
    path('escuela/mensualidades/generar/', api_views.GenerarMensualidadesAPIView.as_view()),
    path('escuela/pagos/', api_views.PagoListCreateAPIView.as_view()),
    path('escuela/pagos/<int:pk>/', api_views.PagoDetailAPIView.as_view()),
    path('escuela/plantillas/', api_views.PlantillaListCreateAPIView.as_view()),
    path('escuela/plantillas/<int:pk>/', api_views.PlantillaDetailAPIView.as_view()),
    path('escuela/mensajes/', api_views.RegistroMensajeListCreateAPIView.as_view()),
    path('escuela/grupos/', api_views.GrupoListCreateAPIView.as_view()),
    path('escuela/grupos/<int:pk>/', api_views.GrupoDetailAPIView.as_view()),
    path('escuela/cambios-horario/', api_views.CambioHorarioListCreateAPIView.as_view()),
    path('escuela/cambios-horario/<int:pk>/', api_views.CambioHorarioDetailAPIView.as_view()),
    path('escuela/descuentos/', api_views.DescuentoListCreateAPIView.as_view()),
    path('escuela/descuentos/<int:pk>/', api_views.DescuentoDetailAPIView.as_view()),
    path('escuela/evaluaciones/', api_views.EvaluacionListCreateAPIView.as_view()),
    path('escuela/evaluaciones/<int:pk>/', api_views.EvaluacionDetailAPIView.as_view()),
    path('escuela/fichas-medicas/', api_views.FichaMedicaListCreateAPIView.as_view()),
    path('escuela/fichas-medicas/<int:pk>/', api_views.FichaMedicaDetailAPIView.as_view()),
    path('escuela/documentos/', api_views.DocumentoListCreateAPIView.as_view()),
    path('escuela/documentos/<int:pk>/', api_views.DocumentoDetailAPIView.as_view()),
    path('escuela/uniformes/', api_views.UniformeListCreateAPIView.as_view()),
    path('escuela/uniformes/<int:pk>/', api_views.UniformeDetailAPIView.as_view()),
    path('escuela/materiales/', api_views.MaterialListCreateAPIView.as_view()),
    path('escuela/materiales/<int:pk>/', api_views.MaterialDetailAPIView.as_view()),
    path('escuela/reportes/', api_views.ReportesEscuelaAPIView.as_view()),
    path('escuela/solicitudes/', api_views.SolicitudInscripcionListCreateAPIView.as_view()),
    path('escuela/solicitudes/<int:pk>/revisar/', api_views.RevisarSolicitudAPIView.as_view()),
    path('escuela/lista-espera/', api_views.ListaEsperaListCreateAPIView.as_view()),
    path('escuela/lista-espera/<int:pk>/', api_views.ListaEsperaDetailAPIView.as_view()),
    path('escuela/gastos/', api_views.GastoListCreateAPIView.as_view()),
    path('escuela/gastos/<int:pk>/', api_views.GastoDetailAPIView.as_view()),
    path('escuela/inventario/', api_views.ProductoInventarioListCreateAPIView.as_view()),
    path('escuela/inventario/<int:pk>/', api_views.ProductoInventarioDetailAPIView.as_view()),
    path('escuela/inventario-movimientos/', api_views.MovimientoInventarioListCreateAPIView.as_view()),
    path('escuela/auditoria/', api_views.AuditoriaListAPIView.as_view()),
]
